name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            Thanks for the issue, we will take it into consideration! Please give us time to get back to you.
                                          
            For full info on how to contribute, please check out our [contributors guide](https://github.com/nextsms/js-client/blob/main/CONTRIBUTING.md).
        pr-message:  |
            Thank you for opening this PR! We appreciate you!                          
            
            A Our Team member will review this contribution and get back to
            you as soon as possible!

